#!/bin/bash
#SBATCH --job-name=MAKERtoGFF
#SBATCH --partition=pibu_el8 
#SBATCH --cpus-per-task=4 
#SBATCH --mem=64G
#SBATCH --time=24:00:00 
#SBATCH --output=/data/users/aikiror/genomeAnnotation/logAndReports/06_MAKER_to_GFF/output_06_MAKER_to_GFF_%j.o
#SBATCH --error=/data/users/aikiror/genomeAnnotation/logAndReports/06_MAKER_to_GFF/error_06_MAKER_to_GFF_%j.e
#SBATCH --mail-user=amo.ikiror@students.unibe.ch
#SBATCH --mail-type=end,fail

#this script will merge separate gff files into 1 and also generate the gene models

#directories
WORKDIR="/data/users/aikiror/genomeAnnotation"
OUTPUTDIR="${WORKDIR}/output/06_MAKER_to_GFF"
COURSEDIR="${WORKDIR}/CDS_annotation"
ASSEMBLY_PREFIX="pacbio_hifi_Est-0.p_ctg"

#path to datastore generated by MAKER
MAKER_OUTPUT="${WORKDIR}/output/05_MAKER_MPI/pacbio_hifi_Est-0.p_ctg.maker.output"
INDEX_LOG="${MAKER_OUTPUT}/pacbio_hifi_Est-0.p_ctg_master_datastore_index.log"

#make path to outputdir if it doesnt exist
mkdir -p ${OUTPUTDIR}

#change paths to outputdir
cd ${OUTPUTDIR}

#containers/modules/tools
MAKERBIN="${COURSEDIR}/softwares/Maker_v3.01.03/src/bin"

#merge individual gffs into one
$MAKERBIN/gff3_merge -s -d ${INDEX_LOG} > ${ASSEMBLY_PREFIX}.all.maker.gff

#####
$MAKERBIN/gff3_merge -n -s -d ${INDEX_LOG} > ${ASSEMBLY_PREFIX}.all.maker.noseq.gff
$MAKERBIN/fasta_merge -d ${INDEX_LOG} -o ${ASSEMBLY_PREFIX}